name: CI PipeLine

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
    
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20
         cache: 'npm'
    
     - name: Install dependencies
       run: npm Install

     - name: Run Lints
       run: npm run lint

     - name: Run Tests
       run: npm test

     - name: Upload test results (runs even tests fails)
       if: always()
       uses: actions/upload-artifact@v4
       with:
        name: test-result
        path: ./ 
